[package]
name = "december"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
argh = "0.1.8"
bytecount = "0.6.3"
lazy_static = "1.4.0"
nom = "7.1.1"
thiserror = "1.0.34"
